// Acervo de frases motivacionais que giram uma por dia no topo do Dashboard.
// Tom sempre positivo e sem culpa (espec. 3.7 — nunca "falhou"/"pecadinho").
// Deliberadamente grande: com poucas frases o usuário repete a mesma toda
// semana e o efeito surpresa/motivação se perde.
export const MOTIVATION_PHRASES: string[] = [
  "Constância vence intensidade 💪",
  "Um treino de cada vez 🔥",
  "Seu único adversário é o de ontem 🚀",
  "Pequenos passos, grandes resultados 🌱",
  "Hoje conta. Sempre conta ✨",
  "Progresso não é linear, e tá tudo bem",
  "Aparecer já é 90% do caminho",
  "Feito é melhor que perfeito",
  "Seu corpo agradece cada escolha boa",
  "Disciplina é lembrar do motivo",
  "Consistência é o verdadeiro segredo",
  "Você não precisa ser extremo, só constante",
  "Cada repetição é um investimento em você",
  "Descanso também é treino 😴",
  "Beber água agora é um presente pro futuro",
  "Ninguém constrói um físico em um dia só",
  "O de hoje já é mais um dia que ontem",
  "Menos perfeição, mais repetição",
  "Você é mais forte do que imagina",
  "Foco no processo, o resultado vem",
  "Sua versão de amanhã agradece a de hoje",
  "Não é sobre motivação, é sobre hábito",
  "Comece pequeno, continue grande",
  "Toda jornada tem dias difíceis — siga",
  "O corpo muda, a mente também",
  "Celebre o que já é diferente há 1 mês",
  "Você é a soma dos seus hábitos diários",
  "Energia boa começa com escolhas boas",
  "Cuidar de você não é luxo, é rotina",
  "Cada treino é uma prova de compromisso",
  "Simples e consistente bate complexo e raro",
  "Confie no processo, ele funciona",
  "Você já percorreu mais do que imagina",
  "Grandes mudanças começam pequenas",
  "Hoje é só mais um degrau 🪜",
  "Sua saúde é sua conquista diária",
  "Menos comparação, mais evolução própria",
  "O importante é continuar aparecendo",
  "Treinar é um ato de autocuidado",
  "Dormir bem também é treinar 💤",
  "Cada gole de água é um voto em você",
  "Não existe treino perdido, só treino feito",
  "Seu ritmo, seu tempo, sua vitória",
  "A jornada é sua — vá no seu passo",
  "Ser consistente é a maior força",
  "Você não precisa de motivação, precisa de rotina",
  "Escolha por você, hoje e sempre",
  "Cada dia é uma nova chance de cuidar de si",
  "O esforço de hoje é o resultado de amanhã",
  "Vai com calma, mas vai todo dia",
  "Sua constância é maior que qualquer desculpa",
  "Orgulhe-se de cada pequeno avanço",
  "Nada de comparação, só evolução",
  "Foque no que você pode controlar hoje",
  "Você está construindo algo que dura",
  "Menos perfeccionismo, mais ação",
  "Hidratação é combustível pro seu dia 💧",
  "Descansar também faz parte do plano",
  "Toda constância começa com um dia só",
  "Sua melhor versão está sendo construída agora",
  "Comemore o esforço, não só o resultado",
];

export function motivationOfTheDay(): string {
  const dayIndex = Math.floor(Date.now() / 86400000);
  return MOTIVATION_PHRASES[dayIndex % MOTIVATION_PHRASES.length];
}
